import type { Category } from "./categories";

/**
 * Curated mock places. These are real, well-known spots with approximate
 * coordinates and neighbourhood-level addresses so the demo feels authentic
 * without a Google Maps key. Hours are indicative only.
 */
export interface MockPlace {
  slug: string;
  name: string;
  city: string;
  country: string;
  category: Category;
  address: string;
  lat: number;
  lng: number;
  hours: string[];
  /** Used by the seed script as an example recommendation. */
  blurb?: string;
}

const H = {
  lunchDinner: ["Mon–Sun: 11:30–14:30, 18:00–22:00"],
  cafe: ["Mon–Sun: 08:00–18:00"],
  late: ["Mon–Thu: 18:00–02:00", "Fri–Sat: 18:00–04:00", "Sun: closed"],
  allDay: ["Mon–Sun: 10:00–22:00"],
  daytime: ["Mon–Sun: 09:00–17:00"],
  temple: ["Mon–Sun: 06:00–17:00"],
  park: ["Open 24 hours"],
  shop: ["Mon–Sat: 10:00–20:00", "Sun: 11:00–18:00"],
  hotel: ["Check-in 15:00 · Check-out 11:00"],
  museum: ["Tue–Sun: 10:00–18:00", "Mon: closed"],
};

export const MOCK_PLACES: MockPlace[] = [
  // ---- Tokyo ----
  { slug: "tsuta-ramen", name: "Tsuta", city: "Tokyo", country: "Japan", category: "Food & Drinks", address: "1-14-1 Sugamo, Toshima City, Tokyo", lat: 35.7336, lng: 139.7391, hours: ["Mon–Sun: 11:00–16:00"], blurb: "Michelin-starred ramen for about ¥1,500. Go right at open or plan to wait an hour." },
  { slug: "yanaka-coffee-ten", name: "Yanaka Coffee Ten", city: "Tokyo", country: "Japan", category: "Food & Drinks", address: "3-8-6 Yanaka, Taito City, Tokyo", lat: 35.7258, lng: 139.7669, hours: H.cafe, blurb: "Tiny stand-up coffee spot. Order the hojicha latte and sit on the steps outside." },
  { slug: "ichiran-shinjuku", name: "Ichiran Shinjuku", city: "Tokyo", country: "Japan", category: "Food & Drinks", address: "3-34-11 Shinjuku, Shinjuku City, Tokyo", lat: 35.6916, lng: 139.7036, hours: ["Open 24 hours"], blurb: "For 2am cravings after a long night. Solo booth, no talking needed." },
  { slug: "golden-gai", name: "Golden Gai", city: "Tokyo", country: "Japan", category: "Nightlife", address: "1 Chome Kabukicho, Shinjuku City, Tokyo", lat: 35.6938, lng: 139.7047, hours: H.late, blurb: "Two hundred bars the size of a closet. Pick one with a hand-written sign and stay for one drink." },
  { slug: "senso-ji", name: "Sensō-ji", city: "Tokyo", country: "Japan", category: "Spiritual", address: "2-3-1 Asakusa, Taito City, Tokyo", lat: 35.7148, lng: 139.7967, hours: H.temple, blurb: "Go at 7am before the crowds. The incense smoke is meant to bring good health, waft it over you." },
  { slug: "meiji-jingu", name: "Meiji Jingu", city: "Tokyo", country: "Japan", category: "Spiritual", address: "1-1 Yoyogikamizonocho, Shibuya City, Tokyo", lat: 35.6764, lng: 139.6993, hours: ["Sunrise to sunset"], blurb: "A forest in the middle of the city. Walk the long gravel path slowly." },
  { slug: "shibuya-sky", name: "Shibuya Sky", city: "Tokyo", country: "Japan", category: "Scenic Spots", address: "2-24-12 Shibuya, Shibuya City, Tokyo", lat: 35.6586, lng: 139.7024, hours: ["Mon–Sun: 10:00–22:30"], blurb: "Book the sunset slot a week ahead. Bring a jacket, it gets windy on the roof." },
  { slug: "teamlab-planets", name: "teamLab Planets", city: "Tokyo", country: "Japan", category: "Entertainment", address: "6-1-16 Toyosu, Koto City, Tokyo", lat: 35.6493, lng: 139.7899, hours: ["Mon–Sun: 09:00–22:00"], blurb: "You walk through water barefoot. Wear shorts or something you can roll up." },
  { slug: "yoyogi-park", name: "Yoyogi Park", city: "Tokyo", country: "Japan", category: "Nature", address: "2-1 Yoyogikamizonocho, Shibuya City, Tokyo", lat: 35.6717, lng: 139.6949, hours: H.park, blurb: "Sunday afternoons: rockabilly dancers by the Harajuku gate, picnics everywhere." },
  { slug: "daikanyama-tsutaya", name: "Daikanyama T-Site", city: "Tokyo", country: "Japan", category: "Shopping", address: "17-5 Sarugakucho, Shibuya City, Tokyo", lat: 35.6491, lng: 139.6997, hours: ["Mon–Sun: 09:00–22:00"], blurb: "The most beautiful bookshop I know. The travel section upstairs has a bar." },
  { slug: "thermae-yu", name: "Thermae-Yu", city: "Tokyo", country: "Japan", category: "Sports & Wellness", address: "1-1-2 Kabukicho, Shinjuku City, Tokyo", lat: 35.6949, lng: 139.7028, hours: ["Open 24 hours"], blurb: "An onsen in Kabukicho. Perfect the morning after Golden Gai." },
  { slug: "trunk-hotel", name: "Trunk Hotel", city: "Tokyo", country: "Japan", category: "Stay", address: "5-31 Jingumae, Shibuya City, Tokyo", lat: 35.6656, lng: 139.7075, hours: H.hotel, blurb: "Small, quiet, walkable to everything in Shibuya and Harajuku." },
  { slug: "fuglen-tokyo", name: "Fuglen Tokyo", city: "Tokyo", country: "Japan", category: "Food & Drinks", address: "1-16-11 Tomigaya, Shibuya City, Tokyo", lat: 35.6683, lng: 139.6901, hours: ["Mon–Sun: 08:00–19:00", "Fri–Sat until 01:00"], blurb: "Norwegian coffee by day, cocktails by night, same room. Sit by the window." },
  { slug: "tsukiji-outer-market", name: "Tsukiji Outer Market", city: "Tokyo", country: "Japan", category: "Shopping", address: "4 Chome Tsukiji, Chuo City, Tokyo", lat: 35.6654, lng: 139.7707, hours: ["Mon–Sat: 05:00–14:00", "Sun: mostly closed"], blurb: "Tamagoyaki on a stick from Yamachou, then uni at whichever stall has the shortest line." },

  // ---- Athens ----
  { slug: "acropolis", name: "Acropolis of Athens", city: "Athens", country: "Greece", category: "Scenic Spots", address: "Athens 105 58, Greece", lat: 37.9715, lng: 23.7257, hours: ["Mon–Sun: 08:00–20:00 (summer)"], blurb: "Book the 8am slot online. By 10 it's a furnace and a queue." },
  { slug: "philopappou-hill", name: "Philopappou Hill", city: "Athens", country: "Greece", category: "Nature", address: "Filopappou, Athens", lat: 37.9686, lng: 23.7195, hours: H.park, blurb: "The best free view of the Acropolis, especially at sunset. Bring a beer." },
  { slug: "to-kafeneio-plaka", name: "To Kafeneio", city: "Athens", country: "Greece", category: "Food & Drinks", address: "Epicharmou 1, Plaka, Athens", lat: 37.9722, lng: 23.7296, hours: H.lunchDinner, blurb: "Old-school mezze in Plaka without the tourist-trap feel. Get the fava and the meatballs." },
  { slug: "six-dogs", name: "Six d.o.g.s", city: "Athens", country: "Greece", category: "Nightlife", address: "Avramiotou 6-8, Monastiraki, Athens", lat: 37.9782, lng: 23.7268, hours: ["Mon–Sun: 10:00–03:00"], blurb: "Café-bar with a garden in the back that turns into a gig venue at night." },
  { slug: "varvakios-market", name: "Varvakios Central Market", city: "Athens", country: "Greece", category: "Shopping", address: "Athinas 42, Athens", lat: 37.9796, lng: 23.7264, hours: ["Mon–Sat: 07:00–15:00", "Sun: closed"], blurb: "Loud, bloody, wonderful. There's a taverna in the meat hall that serves patsas at 5am." },
  { slug: "benaki-museum", name: "Benaki Museum", city: "Athens", country: "Greece", category: "Entertainment", address: "Koumpari 1, Athens", lat: 37.9761, lng: 23.7393, hours: ["Wed–Mon: 10:00–18:00", "Tue: closed"], blurb: "Greek history from antiquity to now in one building, then lunch on the roof terrace." },
  { slug: "little-kook", name: "Little Kook", city: "Athens", country: "Greece", category: "Food & Drinks", address: "Karaiskaki 17, Psyri, Athens", lat: 37.9788, lng: 23.7245, hours: ["Mon–Sun: 10:00–00:00"], blurb: "Ridiculous themed café that changes its whole street decor every season. Go for the cake, stay for the chaos." },
  { slug: "monastiraki-square", name: "Monastiraki Square", city: "Athens", country: "Greece", category: "Scenic Spots", address: "Monastiraki, Athens", lat: 37.976, lng: 23.7257, hours: H.park, blurb: "Flea market on Sundays. Buy a koulouri from the cart on the corner." },
  { slug: "cathedral-of-athens", name: "Metropolitan Cathedral of Athens", city: "Athens", country: "Greece", category: "Spiritual", address: "Mitropoleos, Athens", lat: 37.9755, lng: 23.7299, hours: H.daytime, blurb: "Peek into the tiny Byzantine chapel next door too, it's older and prettier." },
  { slug: "the-foundry-suites", name: "The Foundry Suites", city: "Athens", country: "Greece", category: "Stay", address: "Sarri 40, Psyri, Athens", lat: 37.9797, lng: 23.7225, hours: H.hotel, blurb: "Converted print works with a rooftop that looks straight at the Acropolis." },

  // ---- Mexico City ----
  { slug: "contramar", name: "Contramar", city: "Mexico City", country: "Mexico", category: "Food & Drinks", address: "Durango 200, Roma Norte, Mexico City", lat: 19.4193, lng: -99.1665, hours: ["Mon–Thu: 12:00–18:30", "Fri–Sat: 12:00–20:00", "Sun: 12:00–18:30"], blurb: "Tuna tostadas and the whole grilled fish, half red half green. Book a week ahead for a Friday lunch." },
  { slug: "el-vilsito", name: "El Vilsito", city: "Mexico City", country: "Mexico", category: "Food & Drinks", address: "Av. Universidad 248, Narvarte, Mexico City", lat: 19.3939, lng: -99.1583, hours: ["Mon–Sun: 20:00–04:00"], blurb: "A mechanic's garage by day, the best tacos al pastor in the city by night. Cash only." },
  { slug: "museo-frida-kahlo", name: "Museo Frida Kahlo", city: "Mexico City", country: "Mexico", category: "Entertainment", address: "Londres 247, Coyoacán, Mexico City", lat: 19.3551, lng: -99.1625, hours: ["Tue–Sun: 10:00–18:00", "Mon: closed"], blurb: "Tickets sell out. Buy them online two weeks out, then wander Coyoacán market after." },
  { slug: "chapultepec-park", name: "Bosque de Chapultepec", city: "Mexico City", country: "Mexico", category: "Nature", address: "Miguel Hidalgo, Mexico City", lat: 19.4204, lng: -99.1819, hours: ["Tue–Sun: 05:00–20:00"], blurb: "Twice the size of Central Park. Rent a pedal boat on the lake, it's very silly and very good." },
  { slug: "licoreria-limantour", name: "Licorería Limantour", city: "Mexico City", country: "Mexico", category: "Nightlife", address: "Álvaro Obregón 106, Roma Norte, Mexico City", lat: 19.4194, lng: -99.1602, hours: H.late, blurb: "One of the best bars in the world and it still feels like a neighbourhood spot. Order whatever has mezcal." },
  { slug: "templo-mayor", name: "Templo Mayor", city: "Mexico City", country: "Mexico", category: "Scenic Spots", address: "Seminario 8, Centro Histórico, Mexico City", lat: 19.4348, lng: -99.1316, hours: H.museum, blurb: "The Aztec city, right underneath the colonial one. The museum at the back is worth the extra hour." },
  { slug: "catedral-metropolitana", name: "Catedral Metropolitana", city: "Mexico City", country: "Mexico", category: "Spiritual", address: "Plaza de la Constitución, Centro Histórico, Mexico City", lat: 19.4344, lng: -99.1332, hours: ["Mon–Sun: 08:00–20:00"], blurb: "Notice the plumb line hanging from the dome, it shows how much the building is sinking." },
  { slug: "mercado-de-coyoacan", name: "Mercado de Coyoacán", city: "Mexico City", country: "Mexico", category: "Shopping", address: "Ignacio Allende, Coyoacán, Mexico City", lat: 19.3517, lng: -99.1621, hours: ["Mon–Sun: 08:00–19:00"], blurb: "Tostadas at the stalls in the middle. Get the cochinita and a fresh tamarind agua." },
  { slug: "panaderia-rosetta", name: "Panadería Rosetta", city: "Mexico City", country: "Mexico", category: "Food & Drinks", address: "Colima 179, Roma Norte, Mexico City", lat: 19.4188, lng: -99.1611, hours: ["Mon–Sat: 07:00–21:00", "Sun: 07:00–19:00"], blurb: "The guava roll. Get two. There will be a line, it moves fast." },
  { slug: "casa-luis-barragan", name: "Casa Luis Barragán", city: "Mexico City", country: "Mexico", category: "Entertainment", address: "Gral. Francisco Ramírez 12, Miguel Hidalgo, Mexico City", lat: 19.4112, lng: -99.1921, hours: ["Mon–Fri: 10:00–17:00 (by tour)"], blurb: "Book the tour weeks ahead. It's the pinkest, calmest house you'll ever stand in." },
  { slug: "condesa-df", name: "Condesa DF", city: "Mexico City", country: "Mexico", category: "Stay", address: "Av. Veracruz 102, Condesa, Mexico City", lat: 19.4171, lng: -99.1741, hours: H.hotel, blurb: "Rooftop bar, tree-lined streets, five minutes to Parque México." },

  // ---- Dubai ----
  { slug: "burj-khalifa", name: "Burj Khalifa", city: "Dubai", country: "United Arab Emirates", category: "Scenic Spots", address: "1 Sheikh Mohammed bin Rashid Blvd, Downtown Dubai", lat: 25.1972, lng: 55.2744, hours: ["Mon–Sun: 08:30–23:00"], blurb: "Skip the observation deck queue and book At.mosphere for a coffee on the 122nd floor instead." },
  { slug: "al-fahidi", name: "Al Fahidi Historical Neighbourhood", city: "Dubai", country: "United Arab Emirates", category: "Scenic Spots", address: "Al Fahidi, Bur Dubai", lat: 25.2639, lng: 55.3003, hours: H.park, blurb: "Wind towers, courtyards, and the Arabian Tea House. Go late afternoon when the light goes gold." },
  { slug: "ravi-restaurant", name: "Ravi Restaurant", city: "Dubai", country: "United Arab Emirates", category: "Food & Drinks", address: "Al Satwa Rd, Al Satwa, Dubai", lat: 25.2276, lng: 55.2735, hours: ["Mon–Sun: 05:00–03:00"], blurb: "Pakistani food at plastic tables for almost nothing. Chicken karahi and fresh naan." },
  { slug: "alserkal-avenue", name: "Alserkal Avenue", city: "Dubai", country: "United Arab Emirates", category: "Entertainment", address: "Al Quoz 1, Dubai", lat: 25.1435, lng: 55.2252, hours: H.shop, blurb: "Galleries in warehouses, a cinema, a chocolate factory. The real Dubai art scene." },
  { slug: "jumeirah-mosque", name: "Jumeirah Mosque", city: "Dubai", country: "United Arab Emirates", category: "Spiritual", address: "Jumeirah Beach Rd, Jumeirah 1, Dubai", lat: 25.2338, lng: 55.2657, hours: ["Tours daily at 10:00 (except Fri)"], blurb: "The 10am tour is genuinely welcoming and open about everything. Bring questions." },
  { slug: "gold-souk", name: "Gold Souk", city: "Dubai", country: "United Arab Emirates", category: "Shopping", address: "Al Dhagaya, Deira, Dubai", lat: 25.2723, lng: 55.2974, hours: ["Sat–Thu: 10:00–22:00", "Fri: 16:00–22:00"], blurb: "Take the abra across the creek to get there. Haggle, always." },
  { slug: "kite-beach", name: "Kite Beach", city: "Dubai", country: "United Arab Emirates", category: "Nature", address: "Jumeirah 3, Dubai", lat: 25.1793, lng: 55.2201, hours: H.park, blurb: "Run the track at 6am before the heat, then breakfast at Salt on the sand." },
  { slug: "talise-spa", name: "Talise Spa, Madinat Jumeirah", city: "Dubai", country: "United Arab Emirates", category: "Sports & Wellness", address: "Madinat Jumeirah, Al Sufouh Rd, Dubai", lat: 25.1332, lng: 55.1855, hours: ["Mon–Sun: 09:00–21:00"], blurb: "Arrive early for the outdoor pools. The hammam treatment is the one to book." },
  { slug: "xva-art-hotel", name: "XVA Art Hotel", city: "Dubai", country: "United Arab Emirates", category: "Stay", address: "Al Fahidi Historical Neighbourhood, Bur Dubai", lat: 25.2636, lng: 55.2999, hours: H.hotel, blurb: "A tiny gallery-hotel in the old quarter, the opposite of everything else in Dubai." },
  { slug: "zero-gravity", name: "Zero Gravity", city: "Dubai", country: "United Arab Emirates", category: "Nightlife", address: "Skydive Dubai Drop Zone, Dubai Marina", lat: 25.0906, lng: 55.1394, hours: ["Mon–Sun: 10:00–03:00"], blurb: "Beach club by day, big party on Friday nights. Skydivers land right next to the pool." },

  // ---- Lisbon ----
  { slug: "pasteis-de-belem", name: "Pastéis de Belém", city: "Lisbon", country: "Portugal", category: "Food & Drinks", address: "R. de Belém 84-92, Lisbon", lat: 38.6975, lng: -9.2032, hours: ["Mon–Sun: 08:00–22:00"], blurb: "Skip the takeaway queue and go inside. The rooms in the back are huge and empty." },
  { slug: "time-out-market", name: "Time Out Market Lisboa", city: "Lisbon", country: "Portugal", category: "Food & Drinks", address: "Av. 24 de Julho 49, Cais do Sodré, Lisbon", lat: 38.7071, lng: -9.1457, hours: ["Sun–Wed: 10:00–00:00", "Thu–Sat: 10:00–02:00"], blurb: "Touristy but the Marlene Vieira stall is properly good. Eat, then walk to Pink Street." },
  { slug: "miradouro-santa-luzia", name: "Miradouro de Santa Luzia", city: "Lisbon", country: "Portugal", category: "Scenic Spots", address: "Largo Santa Luzia, Alfama, Lisbon", lat: 38.7118, lng: -9.1303, hours: H.park, blurb: "The bougainvillea terrace over Alfama. There's usually a guy playing guitar at sunset." },
  { slug: "lx-factory", name: "LX Factory", city: "Lisbon", country: "Portugal", category: "Shopping", address: "R. Rodrigues de Faria 103, Alcântara, Lisbon", lat: 38.7035, lng: -9.1784, hours: ["Mon–Sun: 10:00–22:00"], blurb: "Ler Devagar bookshop inside is the reason to go. Sunday flea market too." },
  { slug: "tasca-do-chico", name: "Tasca do Chico", city: "Lisbon", country: "Portugal", category: "Nightlife", address: "R. do Diário de Notícias 39, Bairro Alto, Lisbon", lat: 38.7118, lng: -9.1449, hours: ["Mon–Sun: 19:00–02:00"], blurb: "Free fado, tiny room, get there at 7:30 or stand outside. Order the chouriço that arrives on fire." },
  { slug: "jeronimos-monastery", name: "Jerónimos Monastery", city: "Lisbon", country: "Portugal", category: "Spiritual", address: "Praça do Império, Belém, Lisbon", lat: 38.6979, lng: -9.2068, hours: ["Tue–Sun: 10:00–18:30", "Mon: closed"], blurb: "The cloister is the point. Buy tickets online; the queue outside is brutal." },
  { slug: "jardim-da-estrela", name: "Jardim da Estrela", city: "Lisbon", country: "Portugal", category: "Nature", address: "Praça da Estrela, Lisbon", lat: 38.7139, lng: -9.1602, hours: ["Mon–Sun: 07:00–00:00"], blurb: "A proper neighbourhood park with a kiosk. Get a bica and sit under the trees." },
  { slug: "praia-do-guincho", name: "Praia do Guincho", city: "Lisbon", country: "Portugal", category: "Sports & Wellness", address: "Guincho, Cascais", lat: 38.7327, lng: -9.4735, hours: H.park, blurb: "Windy wild beach 40 minutes out. Surf lessons in the morning, Bar do Guincho after." },
  { slug: "memmo-alfama", name: "Memmo Alfama", city: "Lisbon", country: "Portugal", category: "Stay", address: "Tv. das Merceeiras 27, Alfama, Lisbon", lat: 38.7105, lng: -9.1297, hours: H.hotel, blurb: "Red rooftop pool over the river. Small rooms, huge view." },
  { slug: "museu-nacional-do-azulejo", name: "Museu Nacional do Azulejo", city: "Lisbon", country: "Portugal", category: "Entertainment", address: "R. Me. Deus 4, Lisbon", lat: 38.7248, lng: -9.1136, hours: H.museum, blurb: "Five hundred years of tiles in a convent. The café in the garden is a secret." },

  // ---- London ----
  { slug: "borough-market", name: "Borough Market", city: "London", country: "United Kingdom", category: "Shopping", address: "8 Southwark St, London SE1 1TL", lat: 51.5055, lng: -0.091, hours: ["Tue–Sat: 10:00–17:00", "Sun: 10:00–16:00", "Mon: closed"], blurb: "The Kappacasein toastie, then a Monmouth coffee. Weekday mornings only if you hate crowds." },
  { slug: "dishoom-shoreditch", name: "Dishoom Shoreditch", city: "London", country: "United Kingdom", category: "Food & Drinks", address: "7 Boundary St, London E2 7JE", lat: 51.5246, lng: -0.0768, hours: ["Mon–Sun: 08:00–23:00"], blurb: "Bacon naan roll at breakfast, no queue before 9am. The black daal at dinner." },
  { slug: "the-french-house", name: "The French House", city: "London", country: "United Kingdom", category: "Nightlife", address: "49 Dean St, Soho, London W1D 5BG", lat: 51.5131, lng: -0.1318, hours: ["Mon–Sat: 12:00–23:00", "Sun: 12:00–22:30"], blurb: "No phones, no music, beer only in halves. Soho as it used to be." },
  { slug: "hampstead-heath", name: "Hampstead Heath", city: "London", country: "United Kingdom", category: "Nature", address: "Hampstead, London NW3", lat: 51.5608, lng: -0.1629, hours: H.park, blurb: "Swim in the ponds, then walk up to Parliament Hill for the skyline." },
  { slug: "tate-modern", name: "Tate Modern", city: "London", country: "United Kingdom", category: "Entertainment", address: "Bankside, London SE1 9TG", lat: 51.5076, lng: -0.0994, hours: ["Mon–Sun: 10:00–18:00"], blurb: "Free. Go straight to the Turbine Hall then up to the viewing level in the Blavatnik building." },
  { slug: "columbia-road-flower-market", name: "Columbia Road Flower Market", city: "London", country: "United Kingdom", category: "Shopping", address: "Columbia Rd, London E2 7RG", lat: 51.5292, lng: -0.0698, hours: ["Sun: 08:00–15:00"], blurb: "Sundays only. Get there at 8 or at 2 for bargains, never at 11." },
  { slug: "st-pauls-cathedral", name: "St Paul's Cathedral", city: "London", country: "United Kingdom", category: "Spiritual", address: "St. Paul's Churchyard, London EC4M 8AD", lat: 51.5138, lng: -0.0984, hours: ["Mon–Sat: 08:30–16:30"], blurb: "Climb to the Whispering Gallery and test it, it actually works." },
  { slug: "primrose-hill", name: "Primrose Hill", city: "London", country: "United Kingdom", category: "Scenic Spots", address: "Primrose Hill Rd, London NW1", lat: 51.5395, lng: -0.1607, hours: H.park, blurb: "The best skyline view in London, no ticket needed. Sunset with a bottle from the shop on Regent's Park Road." },
  { slug: "the-hoxton-shoreditch", name: "The Hoxton, Shoreditch", city: "London", country: "United Kingdom", category: "Stay", address: "81 Great Eastern St, London EC2A 3HU", lat: 51.5257, lng: -0.0822, hours: H.hotel, blurb: "Lobby is a great place to work. Breakfast bag hung on your door every morning." },

  // ---- Paris ----
  { slug: "du-pain-et-des-idees", name: "Du Pain et des Idées", city: "Paris", country: "France", category: "Food & Drinks", address: "34 Rue Yves Toudic, 75010 Paris", lat: 48.8706, lng: 2.3628, hours: ["Mon–Fri: 07:00–19:30", "Sat–Sun: closed"], blurb: "The escargot pistache-chocolat. Eat it on the canal five minutes away." },
  { slug: "canal-saint-martin", name: "Canal Saint-Martin", city: "Paris", country: "France", category: "Scenic Spots", address: "Quai de Valmy, 75010 Paris", lat: 48.8718, lng: 2.3655, hours: H.park, blurb: "Picnic on the bank with everyone else at 7pm on a summer evening." },
  { slug: "le-comptoir-general", name: "Le Comptoir Général", city: "Paris", country: "France", category: "Nightlife", address: "84 Quai de Jemmapes, 75010 Paris", lat: 48.8723, lng: 2.3648, hours: ["Mon–Sun: 11:00–02:00"], blurb: "A junk-shop jungle bar hidden down an alley by the canal. Rum punch." },
  { slug: "musee-de-l-orangerie", name: "Musée de l'Orangerie", city: "Paris", country: "France", category: "Entertainment", address: "Jardin des Tuileries, 75001 Paris", lat: 48.8638, lng: 2.3226, hours: ["Wed–Mon: 09:00–18:00", "Tue: closed"], blurb: "Monet's water lilies in two oval rooms. Go at opening and you'll have them to yourself for ten minutes." },
  { slug: "sacre-coeur", name: "Sacré-Cœur", city: "Paris", country: "France", category: "Spiritual", address: "35 Rue du Chevalier de la Barre, 75018 Paris", lat: 48.8867, lng: 2.3431, hours: ["Mon–Sun: 06:30–22:30"], blurb: "Take the funicular up, walk down through the back streets of Montmartre." },
  { slug: "marche-des-enfants-rouges", name: "Marché des Enfants Rouges", city: "Paris", country: "France", category: "Shopping", address: "39 Rue de Bretagne, 75003 Paris", lat: 48.8628, lng: 2.3623, hours: ["Tue–Sat: 08:30–20:30", "Sun: 08:30–17:00"], blurb: "Oldest covered market in Paris. The Moroccan stall and the Japanese bento are the two to fight for." },
  { slug: "hotel-des-grands-boulevards", name: "Hôtel des Grands Boulevards", city: "Paris", country: "France", category: "Stay", address: "17 Bd Poissonnière, 75002 Paris", lat: 48.8713, lng: 2.3453, hours: H.hotel, blurb: "Rooftop bar, courtyard restaurant, walking distance to everything in the 2nd." },

  // ---- Marrakech ----
  { slug: "jemaa-el-fnaa", name: "Jemaa el-Fnaa", city: "Marrakech", country: "Morocco", category: "Scenic Spots", address: "Medina, Marrakech", lat: 31.6258, lng: -7.9891, hours: H.park, blurb: "Go at dusk when the food stalls set up. Stall 31 for the sheep's head, if you dare." },
  { slug: "jardin-majorelle", name: "Jardin Majorelle", city: "Marrakech", country: "Morocco", category: "Nature", address: "Rue Yves Saint Laurent, Gueliz, Marrakech", lat: 31.6417, lng: -8.0033, hours: ["Mon–Sun: 08:00–18:30"], blurb: "Book the first slot. That blue is worth the ticket price." },
  { slug: "nomad", name: "Nomad", city: "Marrakech", country: "Morocco", category: "Food & Drinks", address: "1 Derb Aarjane, Rahba Lakdima, Medina, Marrakech", lat: 31.6284, lng: -7.9852, hours: ["Mon–Sun: 12:00–23:00"], blurb: "Modern Moroccan on a rooftop over the spice square. Sunset table on the top level." },
  { slug: "les-bains-de-marrakech", name: "Les Bains de Marrakech", city: "Marrakech", country: "Morocco", category: "Sports & Wellness", address: "2 Derb Sedra, Bab Agnaou, Medina, Marrakech", lat: 31.6199, lng: -7.9897, hours: ["Mon–Sun: 09:00–20:00"], blurb: "Traditional hammam with black soap and a proper scrub. Book the day you land." },
  { slug: "souk-semmarine", name: "Souk Semmarine", city: "Marrakech", country: "Morocco", category: "Shopping", address: "Souk Semmarine, Medina, Marrakech", lat: 31.6288, lng: -7.9878, hours: ["Mon–Sun: 09:00–21:00"], blurb: "Start here and get lost on purpose. Leather in the north, lanterns in the east." },
  { slug: "riad-yasmine", name: "Riad Yasmine", city: "Marrakech", country: "Morocco", category: "Stay", address: "209 Rue Diour Saboun, Medina, Marrakech", lat: 31.6349, lng: -7.9896, hours: H.hotel, blurb: "The green-tiled courtyard pool you've seen on every feed. It's small but it's real." },
  { slug: "koutoubia-mosque", name: "Koutoubia Mosque", city: "Marrakech", country: "Morocco", category: "Spiritual", address: "Avenue Mohammed V, Medina, Marrakech", lat: 31.6238, lng: -7.9937, hours: ["Gardens open daily"], blurb: "Non-Muslims can't go in, but the gardens around it at sunset are the calmest spot in the medina." },

  // ---- New York ----
  { slug: "russ-and-daughters", name: "Russ & Daughters", city: "New York", country: "United States", category: "Food & Drinks", address: "179 E Houston St, New York, NY 10002", lat: 40.7224, lng: -73.9882, hours: ["Mon–Sun: 08:00–18:00"], blurb: "Take a number. Classic bagel with nova and a side of whitefish salad." },
  { slug: "brooklyn-bridge-park", name: "Brooklyn Bridge Park", city: "New York", country: "United States", category: "Nature", address: "334 Furman St, Brooklyn, NY 11201", lat: 40.7003, lng: -73.9967, hours: ["Mon–Sun: 06:00–01:00"], blurb: "Walk across the bridge from Manhattan, then Pier 1 for the skyline at golden hour." },
  { slug: "the-met", name: "The Metropolitan Museum of Art", city: "New York", country: "United States", category: "Entertainment", address: "1000 5th Ave, New York, NY 10028", lat: 40.7794, lng: -73.9632, hours: ["Sun–Thu: 10:00–17:00", "Fri–Sat: 10:00–21:00"], blurb: "Pick two wings, not twenty. The roof garden bar in summer." },
  { slug: "attaboy", name: "Attaboy", city: "New York", country: "United States", category: "Nightlife", address: "134 Eldridge St, New York, NY 10002", lat: 40.7187, lng: -73.9919, hours: ["Mon–Sun: 18:00–02:00"], blurb: "No menu. Tell them what you like and trust them. Knock on the metal door." },
  { slug: "chelsea-market", name: "Chelsea Market", city: "New York", country: "United States", category: "Shopping", address: "75 9th Ave, New York, NY 10011", lat: 40.7424, lng: -74.0061, hours: ["Mon–Sat: 07:00–21:00", "Sun: 08:00–20:00"], blurb: "Los Tacos No. 1 inside, then straight up the stairs onto the High Line." },
  { slug: "the-high-line", name: "The High Line", city: "New York", country: "United States", category: "Scenic Spots", address: "New York, NY 10011", lat: 40.748, lng: -74.0048, hours: ["Mon–Sun: 07:00–22:00"], blurb: "Walk it north to south in the late afternoon and end at Chelsea Market." },
  { slug: "ace-hotel-brooklyn", name: "Ace Hotel Brooklyn", city: "New York", country: "United States", category: "Stay", address: "252 Schermerhorn St, Brooklyn, NY 11217", lat: 40.688, lng: -73.9832, hours: H.hotel, blurb: "Concrete and warm wood, great lobby coffee, ten minutes on the subway to Manhattan." },

  // ---- Istanbul ----
  { slug: "ciya-sofrasi", name: "Çiya Sofrası", city: "Istanbul", country: "Türkiye", category: "Food & Drinks", address: "Caferağa, Güneşli Bahçe Sk. 43, Kadıköy, Istanbul", lat: 40.9898, lng: 29.0257, hours: ["Mon–Sun: 11:00–22:00"], blurb: "Anatolian home cooking, point at what looks good. The candied pumpkin dessert with tahini." },
  { slug: "hagia-sophia", name: "Hagia Sophia", city: "Istanbul", country: "Türkiye", category: "Spiritual", address: "Sultan Ahmet, Ayasofya Meydanı, Fatih, Istanbul", lat: 41.0086, lng: 28.9802, hours: ["Mon–Sun: 09:00–19:00 (closed during prayers)"], blurb: "Go at 9am or after 5pm. The upstairs gallery mosaics are the reason to pay for the visitor entrance." },
  { slug: "kadikoy-market", name: "Kadıköy Market", city: "Istanbul", country: "Türkiye", category: "Shopping", address: "Caferağa, Kadıköy, Istanbul", lat: 40.9892, lng: 29.0252, hours: ["Mon–Sun: 08:00–20:00"], blurb: "Take the ferry from Karaköy, wander the fish stalls, stop at every pickle shop." },
  { slug: "cagaloglu-hamami", name: "Cağaloğlu Hamamı", city: "Istanbul", country: "Türkiye", category: "Sports & Wellness", address: "Alemdar, Prof. Kazım İsmail Gürkan Cd. 34, Fatih, Istanbul", lat: 41.0103, lng: 28.9758, hours: ["Mon–Sun: 08:00–22:00"], blurb: "Three hundred years old. Book the full scrub and let them do their thing." },
  { slug: "galata-tower", name: "Galata Tower", city: "Istanbul", country: "Türkiye", category: "Scenic Spots", address: "Bereketzade, Galata Kulesi, Beyoğlu, Istanbul", lat: 41.0256, lng: 28.9742, hours: ["Mon–Sun: 08:30–23:00"], blurb: "Skip the tower queue; sit at the tea garden below and look up. The streets around it are the point." },
  { slug: "arkaoda", name: "Arkaoda", city: "Istanbul", country: "Türkiye", category: "Nightlife", address: "Caferağa, Kadife Sk. 18, Kadıköy, Istanbul", lat: 40.9878, lng: 29.0274, hours: ["Mon–Sun: 14:00–02:00"], blurb: "Kadıköy's living-room bar. DJs in the back, garden out front, everyone you'll meet in Istanbul is here." },
];
